[tox]
minversion = 1.8
envlist = py39
skipsdist = true

[testenv]
passenv = *
setenv =
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS = 1
deps =
    ansible-base==2.10.17
    molecule==3.6.1
    molecule-podman==1.1.0
    ansible-compat==1.0.0
commands =
    # Установка необходимой коллекции внутри venv tox
    ansible-galaxy collection install containers.podman
    molecule test -s podman --destroy always
