---
- name: "Установка Vector"
  ansible.builtin.include_tasks: install.yml

- name: "Настройка Vector"
  ansible.builtin.include_tasks: configure.yml

- name: "Запуск Vector"
  ansible.builtin.include_tasks: service.yml