---
- name: restart vector
  ansible.builtin.systemd:
    name: vector
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  when: ansible_service_mgr == "systemd"

- name: restart vector (контейнер)
  ansible.builtin.shell: pkill vector || true
  become: true
  ignore_errors: true
  when: ansible_service_mgr != "systemd"