---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Проверка | Vector установлен
      ansible.builtin.command: which vector
      register: vector_path
      failed_when: vector_path.rc != 0
      changed_when: false

    - name: Проверка | Версия Vector
      ansible.builtin.command: vector --version
      register: vector_version
      failed_when: vector_version.rc != 0
      changed_when: false

    - name: Проверка | Конфигурационный файл существует
      ansible.builtin.stat:
        path: /etc/vector/vector.yaml
      register: vector_config
      failed_when: not vector_config.stat.exists
      changed_when: false

    - name: Проверка | Конфигурация валидна
      ansible.builtin.command: vector validate --config-yaml /etc/vector/vector.yaml
      register: vector_validate
      failed_when: vector_validate.rc != 0
      changed_when: false

    - name: Проверка | Пользователь vector существует
      ansible.builtin.user:
        name: vector
        state: present
      check_mode: true
      register: vector_user
      failed_when: vector_user is changed
      changed_when: false

    - name: Вывод версии
      ansible.builtin.debug:
        msg: "Vector version: {{ vector_version.stdout }}"